// @ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/66131fb21feec232b4f62d19.glb
** this caused an issue where the display of the model was buggy, the head wasn't displaying, etc
### use this option instead per instructor direction => https://gltf.pmnd.rs/
### drag+drop glb file from ready player one avatar creator
*/

import React from 'react';
import { useGLTF, useFBX, useAnimations } from '@react-three/drei';
import { Outlines, Wireframe } from '@react-three/drei';

export const Avatar = ({ animation }: { animation: string }) => {
  const { nodes, materials } = useGLTF('models/66131fb21feec232b4f62d19.glb');
  // TODO: replace temp. solution to ref complaint
  const groupRef = React.useRef<THREE.Group>(null);

  // const { headFollow, cursorFollow, wireframe } = useControls({
  //   headFollow: false,
  //   cursorFollow: false,
  //   wireframe: false,
  // });

  const { animations } = useFBX(`animations/${animation}.fbx`);
  animations[0].name = `${animation}`;

  const { actions } = useAnimations(animations, groupRef);

  // very hacking to remove ts complaints
  // useFrame((state) => {
  //   if (headFollow && groupRef && groupRef.current) {
  //     const target = new THREE.Vector3(state.mouse.x, state.mouse.y, 1);
  //     (groupRef.current as THREE.Object3D).getObjectByName('Head')!.lookAt(target);
  //   }
  // });

  React.useEffect(() => {
    actions[animation]?.reset().fadeIn(0.5).play();
  }, [actions, animation]);

  return (
    <>
      <group ref={groupRef} dispose={null}>
        <group rotation={[-Math.PI * 0.5, 0, 0]}>
          <primitive object={nodes.Hips} />
          <skinnedMesh
            name="EyeLeft"
            frustumCulled={false}
            geometry={nodes.EyeLeft.geometry}
            material={materials.Wolf3D_Eye}
            skeleton={nodes.EyeLeft.skeleton}
            morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
            morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
          />
          <skinnedMesh
            name="EyeRight"
            frustumCulled={false}
            geometry={nodes.EyeRight.geometry}
            material={materials.Wolf3D_Eye}
            skeleton={nodes.EyeRight.skeleton}
            morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
            morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
          />
          <skinnedMesh
            name="Wolf3D_Head"
            frustumCulled={false}
            geometry={nodes.Wolf3D_Head.geometry}
            material={materials.Wolf3D_Skin}
            skeleton={nodes.Wolf3D_Head.skeleton}
            morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
            morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
          />
          <skinnedMesh
            name="Wolf3D_Teeth"
            frustumCulled={false}
            geometry={nodes.Wolf3D_Teeth.geometry}
            material={materials.Wolf3D_Teeth}
            skeleton={nodes.Wolf3D_Teeth.skeleton}
            morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
            morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.Wolf3D_Hair.geometry}
            material={materials.Wolf3D_Hair}
            skeleton={nodes.Wolf3D_Hair.skeleton}
          >
            <Wireframe thickness={0.1} strokeOpacity={0.5} simplify stroke={'black'} />
            <Outlines thickness={0.01} color={'black'} />
          </skinnedMesh>
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.Wolf3D_Body.geometry}
            material={materials.Wolf3D_Body}
            skeleton={nodes.Wolf3D_Body.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
            material={materials.Wolf3D_Outfit_Bottom}
            skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
            material={materials.Wolf3D_Outfit_Footwear}
            skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.Wolf3D_Outfit_Top.geometry}
            material={materials.Wolf3D_Outfit_Top}
            skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
          >
            <Outlines thickness={0.005} color={'black'} />
          </skinnedMesh>
        </group>
      </group>
    </>
  );
};

useGLTF.preload('models/66131fb21feec232b4f62d19.glb');
