/*
Auto-generated by: https://github.com/pmndrs/gltfjsx && https://gltf.pmnd.rs/
Chair by CMHT Oculus [CC-BY] via Poly Pizza
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';

// @ts-ignore
// eslint-disable-next-line  @typescript-eslint/no-explicit-any
export const Chair = (props: any) => {
  const { nodes, materials } = useGLTF('models/Chair.glb');
  const chairRef = React.useRef<THREE.Group>(null);
  return (
    <group ref={chairRef} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Node-Mesh'].geometry}
        material={materials.Executive}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Node-Mesh_1'].geometry}
        material={materials.Executive__1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Node-Mesh_2'].geometry}
        material={materials.Executive__2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Node-Mesh_3'].geometry}
        material={materials.Executive__3}
      />
    </group>
  );
};

useGLTF.preload('models/Chair.glb');
