/*
Auto-generated by: https://github.com/pmndrs/gltfjsx && https://gltf.pmnd.rs/
*/

import React from 'react';
import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';

// @ts-ignore
// eslint-disable-next-line  @typescript-eslint/no-explicit-any
export const Plant = (props: any) => {
  const { nodes, materials } = useGLTF('models/Houseplant.glb');
  const plantRef = React.useRef<THREE.Mesh>(null);

  return (
    <group ref={plantRef} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['plant_01_Cube006-Mesh'].geometry}
        material={materials['795548']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['plant_01_Cube006-Mesh_1'].geometry}
        material={materials['8BC34A']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['plant_01_Cube006-Mesh_2'].geometry}
        material={materials.F8BBD0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['plant_01_Cube006-Mesh_3'].geometry}
        material={materials['455A64']}
      />
    </group>
  );
};

useGLTF.preload('models/Houseplant.glb');
