/*
Auto-generated by: https://github.com/pmndrs/gltfjsx && https://gltf.pmnd.rs/

*/

import React from 'react';
import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';

// @ts-ignore
// eslint-disable-next-line  @typescript-eslint/no-explicit-any
export const Monitor = (props: any) => {
  const { nodes, materials } = useGLTF('models/Computer Screen.glb');
  const monitorRef = React.useRef<THREE.Group>(null);

  return (
    <group ref={monitorRef} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.computerScreen_2.geometry}
        material={materials.metalDark}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.computerScreen_2_1.geometry}
        material={materials.metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.computerScreen_3.geometry}
        material={materials.metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.computerScreen_3_1.geometry}
        material={materials.metalDark}
      />
    </group>
  );
};

useGLTF.preload('models/Computer Screen.glb');
