/*
Auto-generated by: https://github.com/pmndrs/gltfjsx && https://gltf.pmnd.rs/
Computer mouse by Poly by Google [CC-BY] via Poly Pizza
*/

import React from 'react';
import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';

// @ts-ignore
// eslint-disable-next-line  @typescript-eslint/no-explicit-any
export const Mouse = (props: any) => {
  const { nodes, materials } = useGLTF('models/Computer mouse.glb');
  const mouseRef = React.useRef<THREE.Mesh>(null);
  return (
    <group ref={mouseRef} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ComputerMouse_mesh.geometry}
        material={materials.ComputerMouse_mat1}
      />
    </group>
  );
};

useGLTF.preload('models/Computer mouse.glb');
