/*
Auto-generated by: https://github.com/pmndrs/gltfjsx && https://gltf.pmnd.rs/
 Mug With Office Tool by CreativeTrio
*/
import React from 'react';
import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';

// @ts-ignore
// eslint-disable-next-line  @typescript-eslint/no-explicit-any
export const OfficeTools = (props: any) => {
  const { nodes, materials } = useGLTF('models/Mug With Office Tool.glb');
  const officeToolsRef = React.useRef<THREE.Mesh>(null);

  return (
    <group ref={officeToolsRef} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mug_with_office_tools.geometry}
        material={materials.Material}
      />
    </group>
  );
};

useGLTF.preload('models/Mug With Office Tool.glb');
