/*
Auto-generated by: https://github.com/pmndrs/gltfjsx && https://gltf.pmnd.rs/
*/

import React from 'react';
import * as THREE from 'three';
import { useGLTF, Outlines } from '@react-three/drei';

// @ts-ignore
// eslint-disable-next-line  @typescript-eslint/no-explicit-any
export const Rug = (props: any) => {
  const { nodes, materials } = useGLTF('models/Modern rug.glb');
  const rugRef = React.useRef<THREE.Mesh>(null);
  return (
    <group ref={rugRef} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Modern_rug_Plane004-Mesh'].geometry}
        material={materials['78909C']}
      >
        <Outlines />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Modern_rug_Plane004-Mesh_1'].geometry}
        material={materials['455A64']}
      >
        <Outlines />
      </mesh>
    </group>
  );
};

useGLTF.preload('models/Modern rug.glb');
