/*
Auto-generated by: https://github.com/pmndrs/gltfjsx && https://gltf.pmnd.rs/
Skateboard by Poly by Google [CC-BY] via Poly Pizza
*/

import React from 'react';
import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';

// @ts-ignore
// eslint-disable-next-line  @typescript-eslint/no-explicit-any
export const Skateboard = (props: any) => {
  const { nodes, materials } = useGLTF('models/Skateboard.glb');
  const skateboardRef = React.useRef<THREE.Mesh>(null);
  return (
    <group ref={skateboardRef} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Skateboard.geometry}
        material={materials.Mat}
      />
    </group>
  );
};

useGLTF.preload('models/Skateboard.glb');
