/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Houseplant by Quaternius
*/

import React from 'react';
import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';

// @ts-ignore
// eslint-disable-next-line  @typescript-eslint/no-explicit-any
export const SpiderPlant = (props: any) => {
  const { nodes, materials } = useGLTF('models/SpiderPlant.glb');
  const spiderPlantRef = React.useRef<THREE.Mesh>(null);

  return (
    <group ref={spiderPlantRef} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Houseplant_4_1.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Houseplant_4_2.geometry}
          material={materials.Brown}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Houseplant_4_3.geometry}
          material={materials.Plant_Green}
        />
      </group>
    </group>
  );
};

useGLTF.preload('models/SpiderPlant.glb');
