// Random IT joks :)

const jokes: string[] = [
  'I changed my password to "incorrect". So whenever I forget what it is the computer will say "Your password is incorrect"',
  'Moses had the first tablet that could connect to the cloud',
  'A clean house is the sign of a broken computer',
  "Why do Java developers wear glasses? Because they don't C#",
  'The first computer dates back to Adam and Eve. It was an Apple with limited memory, just one byte. And then everything crashed',
  'Why are PCs like air conditioners? They stop working properly if you open Windows!',
  'What did the turkey say to the computer? Google, google, google!',
  'There are 10 types of people in this world, those who understand binary and those who dont',
  "OOP sucks and this one isn't a joke",
  'What did the robot say to the dead robot? Rust-in-peace',
  'Why do programmers prefer dark mode? Because light attracts bugs!',
  "Why was the JavaScript developer sad? Because he didn't know how to 'null' his feelings.",
  'Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25!',
  'Why do programmers dislike nature? It has too many bugs.',
  "Why do programmers prefer iOS development? Because it's a fruitier experience.",
  "Why was the developer fired from the juice company? He couldn't concentrate.",
  'Why was the computer cold? It left its Windows open.',
  "Why did the programmer quit his job? Because he didn't get arrays.",
  "Why do programmers prefer dark chocolate? It's a better byte size.",
  'Why do programmers prefer git over their girlfriends? Because git never leaves.',
  'Why do programmers prefer Linux? Because rebooting is for installing updates, not fixing crashes.',
  'Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25!',
  'Why do programmers hate nature? It has too many bugs.',
  'Why do programmers prefer dark mode? Because light attracts bugs!',
  "Why couldn't the leopard play hide and seek? Because he was always spotted.",
  "Why was the JavaScript developer sad? Because he didn't know how to 'null' his feelings.",
  "Why do Java developers wear glasses? Because they can't C#.",
  "Why do programmers prefer iOS development? Because it's a fruitier experience.",
  'Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25!',
  'Why do programmers dislike nature? It has too many bugs.',
];

export default jokes;
